### PR TITLE
Capitalize

### PR DESCRIPTION
**Pull request by Intoprelised**
lol

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
You know you need to change the actual file names if you gonna include them with that name

**Comment by MrDiamond64** [comment]
Why does "Set0ffHandCommand.h" have a zero?

**Comment by Intoprelised** [comment]
> Why does "Set0ffHandCommand.h" have a zero?

i fixed it

**Comment by Intoprelised** [comment]
fuck i closed it by accident

**Pull request closed without merging**
