### PR TITLE
adds night mode

### PR DESCRIPTION
**Pull request by ghost**
@OhBoyItsGrelAgain 
Ill add some options (request of grelly), this idea came from rainbow sky and allows you to make the skybox darker similar to that of csgo cheats. For now enjoy my tranny code

### CODE REVIEW

**Comment by gamesense-pub** [comment]
cool, add this!!!

**Comment by ghost** [comment]
> 
> 
> cool, add this!!!

yes vro))))

**Comment by ghost** [comment]
please fix bad code i know im retarded

**Comment by ghost** [comment]
gaming

**Comment by ghost** [comment]
> 
> 
> gaming

i agree :flushed:

**Comment by ghost** [comment]
sorry greloom btw i cba to add purple mode you can do that for me 😳

**Comment by richardletshacks** [comment]
no

**Comment by ghost** [comment]
> 
> 
> no

balls

**Comment by ghost** [comment]
> 
> 
> no

richard daddy pls tell everyone to use rocket chat :pleading:

**Comment by GodGamer029** [comment]
NightMode already exists in the TestModule 10 lines below your addition. good idea doe, will do

**Pull request closed without merging**
