### PR TITLE
Epic Horion Update

### PR DESCRIPTION
**Pull request by Drosh23**

### CODE REVIEW

**Comment by grajkogj** [comment]
why

**Comment by FloppyDolphin57** [comment]
This is the definition of not knowing anything about coding.

**Comment by Aspagisum** [comment]
best coder 🤗🤗🤗🤗🤗🤗☝☝☝☝👍👍👍👍👍👍👍👍👍

**Comment by MrDiamond64** [comment]
wow super pog leet update 69420 new hacker !!!!

**Comment by Drosh23** [comment]
> This is the definition of not knowing anything about coding.

What did I code

**Pull request closed without merging**
