### PR TITLE
Fix CrystalAura Autoselect v2

### PR DESCRIPTION
**Pull request by Intoprelised**
richard u better not deny this

### CODE REVIEW

**Comment by Intoprelised** [comment]
like atleast try it

**Review by N0tExisting — CHANGES_REQUESTED** [review]
Please be context aware, this does not produce the original intended functionality.

**Comment by Intoprelised** [comment]
> Please be context aware, this does not produce the original intended functionality.

What exaclty was it itended to do?

**Comment by Intoprelised** [comment]
I can make it switch back

**Comment by Intoprelised** [comment]
well im closing it

**Pull request closed without merging**
