### PR TITLE
fix Click Gui clicking issue, fix ClickTP and updated AntiBot to include 1.16-1.17 mobs

### PR DESCRIPTION
**Pull request by weedelbhoy1**

### CODE REVIEW

**Comment by OldGreggo5081** [comment]
sexy looking

**Comment by Intoprelised** [comment]
agree

**Comment by OldGreggo5081** [comment]
> ive been using this isint this the right one? https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values

no thats the old ids that are for 1.14, del updated them for .17

**Comment by weedelbhoy1** [comment]
the ids are 100% correct because I made a command that prints the ids on screen, so basically I do the following. I .give the name of the item, then do .id item, then .give id of the item to be sure. and its correct. its very simple tbh.

**Pull request merged**
