### PR TITLE
Refactor module onTick

### PR DESCRIPTION
**Pull request by Synx173**

### CODE REVIEW

**Comment by richardletshacks** [comment]
Why would this need a refactor?

I'd rename ``getGm()`` to ``getGamemode()`` to make it more clear

You should also make the parameter naming of the overriding functions more consistent, some do take ``plr`` as an argument while others take ``player``.

**Comment by Intoprelised** [comment]
> Why would this need a refactor?
> 
> I'd rename `getGm()` to `getGamemode()` to make it more clear
> 
> You should also make the parameter naming of the overriding functions more consistent, some do take `plr` as an argument while others take `player`.

https://github.com/horionclient/Horion/blob/master/Memory/Hooks.cpp#L272

**Comment by richardletshacks** [comment]
The modules are still using GameMode though

**Comment by Synx173** [comment]
> The modules are still using GameMode though

You still need GameMode to build blocks, attack, destroy blocks, etc

**Pull request closed without merging**
