### PR TITLE
Updated a lot of sigs I think

### PR DESCRIPTION
**Pull request by Intoprelised**

### CODE REVIEW

**Comment by Imrglop** [comment]
i think sm tick only gets called while you're destroying blocks

**Comment by Intoprelised** [comment]
> i think sm tick only gets called while you're destroying blocks

i think i updated a lot of the sigs

**Comment by Thekingpenguins** [comment]
wow very gameing

**Comment by richardletshacks** [comment]
doesn't seem to be working for me

**Comment by Intoprelised** [comment]
> doesn't seem to be working for me

il test it

**Pull request closed without merging**
