### PR TITLE
target hud addon to killaura

### PR DESCRIPTION
**Pull request by shape1234**

### CODE REVIEW

**Comment by GodGamer029** [comment]
Your code does not compile

**Comment by hrkyr** [comment]
idk why it says "create killaura.h" but yea

**Comment by rxversedcode** [comment]
idk why it says "create killaura.h" but yea

**Comment by hrkyr** [comment]
so confusing

**Comment by richardletshacks** [comment]
Screenshots would be nice if proposing something visual

**Comment by hrkyr** [comment]
i sent it to you on discord
[here is it for everyone else](https://streamable.com/ud7e31)

**Comment by Thekingpenguins** [comment]
sexy

**Comment by richardletshacks** [comment]
I suggest adding more information to the HUD, not just distance, otherwise I'll close this for having too less relevance to be merged

**Comment by shape1234** [comment]
well ok
i'm going to check the error and fix it & add more things

**Comment by shape1234** [comment]
also rxversed changed the color scheme, no clue why

**Comment by shape1234** [comment]
added facing check
if you are facing
Facing: true
in green
if not
Facing: false
in red

**Comment by shape1234** [comment]
i will try to add a combo counter if you are trying to seem legit

**Comment by shape1234** [comment]
combo rating** 0 to infinity because the combo counter is adding more then 1 every hit

**Comment by GodGamer029** [comment]
This should be in its own module, as it exceeds the definition of 'Killaura', otherwise nice addition

**Comment by hrkyr** [comment]
i mean it isnt really customizable so it really doesn't have any need to be a separate module, it can just be on killaura

**Comment by riesters** [comment]
> i mean it isnt really customizable so it really doesn't have any need to be a separate module, it can just be on killaura

Just put it in noslow 🤑

**Comment by hrkyr** [comment]
your a grown man riester, think about it.

**Comment by Imrglop** [comment]
> > i mean it isnt really customizable so it really doesn't have any need to be a separate module, it can just be on killaura
> 
> Just put it in noslow 🤑

true

**Comment by Wendys-corp** [comment]
fish bucket nbt works now can you update cbe to use fish bucket nbt

**Comment by hrkyr** [comment]
> fish bucket nbt works now can you update cbe to use fish bucket nbt

can you stfu you have been spaming that

**Comment by richardletshacks** [comment]
closed for now, open a new pr when requested changes have been made

**Pull request closed without merging**
