### PR TITLE
Added airplace to scaffold

### PR DESCRIPTION
**Pull request by Intoprelised**
horion scaffold bad so i makes it better

### CODE REVIEW

**Comment by richardletshacks** [comment]
what
your implementation makes no sense

**Comment by PacketDeveloper** [comment]
lmaoooo

**Comment by Intoprelised** [comment]
> what
> your implementation makes no sense

it's safer, because it dosnt need to have a block beside to place

**Comment by Intoprelised** [comment]
e

**Comment by GodGamer029** [comment]
What problem is this pr trying to fix? Last i checked scaffold worked fine

**Comment by Intoprelised** [comment]
> What problem is this pr trying to fix? Last i checked scaffold worked fine

It works fine, but u fall so much its kinda bad

**Pull request closed without merging**
