### PR TITLE
commented out MobPacket in Scaffold to stop the crashing on servers and fix noHurtCam completely. 

### PR DESCRIPTION
**Pull request by weedelbhoy1**

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
Not really a fix

**Comment by Intoprelised** [comment]
i do need this crash fixed

**Comment by weedelbhoy1** [comment]
> Not really a fix

well someone has to fix MobPacket then or you can apply this to stop the crashing. (editied title to better reflect what ive done)

**Comment by weedelbhoy1** [comment]
and better yet when was the last time spoof even worked

**Comment by weedelbhoy1** [comment]
> i do need this crash fixed

i haven't fixed spoof/mob packet. but this does stop the crashing

**Comment by weedelbhoy1** [comment]
fixed NoHurtCam completely

look straight down as far as possible. then enable noHurtCam you will notice the camera shift ever so slighty up, now attempt to run foward. you will run backwards.

what does this simple value change do.

it fixes those 2 issues.

it fixes the camera position 100% and fixes the walking backwards bug if you are looking straight down as far as possible

**Comment by Imrglop** [comment]
I would separate the nohurtcam change and the other stuff into 2 different PRs

**Comment by Intoprelised** [comment]
`！ＰｏＴ　ｎＯ　ｔＮｅＩｌＣ　ｔＳｏＨｇ`

**Comment by richardletshacks** [comment]
yea no, lets just wait for someone to fix it

**Pull request closed without merging**
