### PR TITLE
Fix NoHurtCam 180 flip bug, fix auto totem, fix entity vtable

### PR DESCRIPTION
**Pull request by FloppyDolphin57**

### CODE REVIEW

**Comment by Intoprelised** [comment]
sig yes

**Comment by Intoprelised** [comment]
what do either of those even do

**Comment by FloppyDolphin57** [comment]
> what do either of those even do

i dont even think they are used i just like how the log file doesnt tell me there are dead sigs

**Comment by FloppyDolphin57** [comment]
oops didnt mean to include xp

**Comment by Intoprelised** [comment]
nohurtcam is bugy

**Pull request merged**
