### PR TITLE
Removed blue fog from NightMode, renamed it to TimeChanger

### PR DESCRIPTION
**Pull request by ghost**
The blue fog looked really cringe and ruined How NightMode looked, so I have removed it.
I have also given it the much more suitable name of "TimeChanger".
image
Minecraft 02_09_2020 8_43_09 PM
In these screenshots you can see how it no longer gives the sky that odd blue colour.

### CODE REVIEW

**Comment by baseds** [comment]
this doesnt change the time though

**Comment by GodGamer029** [comment]
Should've been a new module instead of changing the old one

**Comment by savvyuhhh** [comment]
good job

**Comment by baseds** [comment]
also the file name hasn't changed even though you've renamed the module

**Comment by ghost** [comment]
I tried changing the file name, it fucked up cmake so i gave up.

**Pull request closed without merging**
