### PR TITLE
Tiny change to tabGUI.cpp

### PR DESCRIPTION
**Pull request by Damakermiddle**
Don't name variables as something random, it harms users that try to learn and read the code.

### CODE REVIEW

**Comment by ghost** [comment]
theres so much more meme code in horion. lots of yeets, yots and yikes

**Comment by Damakermiddle** [comment]
@d1gress Can u add on to this??

**Comment by richardletshacks** [comment]
Na we keep the meme vars alive

**Comment by Damakermiddle** [comment]
wtf

**Comment by Damakermiddle** [comment]
lmfao

**Comment by Damakermiddle** [comment]
gay
no

**Pull request closed without merging**
