### PR TITLE
Horion Discord has died

### PR DESCRIPTION
**Pull request by Intoprelised**
This pull request isint meant to be accepted im just saying

### CODE REVIEW

**Comment by Hellscaped** [comment]
True true true m8

**Comment by MrDiamond64** [comment]
Guessing by the status of this repo, it probably won't come back any time soon

**Comment by Deadly420** [comment]
RIP

**Comment by dexteratyt** [comment]
rip horion 2022 pubg editon :(

**Comment by dexteratyt** [comment]
> Guessing by the status of this repo, it probably won't come back any time soon

might.

**Comment by Intoprelised** [comment]
hello gamer

**Pull request merged**
