### PR TITLE
StorageESP

### PR DESCRIPTION
**Pull request by Intoprelised**

### CODE REVIEW

**Comment by Intoprelised** [comment]
https://discord.com/channels/732833913705201736/829845858131902465/886620474673623130
image ^

**Comment by Intoprelised** [comment]
https://media.discordapp.net/attachments/829845858131902465/886620472740032582/deez_esps.png
image

**Comment by Intoprelised** [comment]
oop

**Comment by Intoprelised** [comment]
why is it failing

**Comment by N0tExisting** [comment]
> why is it failing

@Intoprelised You need to update the workspace too (`Horion.vcxproj`)

**Comment by Intoprelised** [comment]
> > why is it failing
> 
> @Intoprelised You need to update the workspace too (`Horion.vcxproj`)
Thanks

**Pull request merged**
