### PR TITLE
Fixed .dupe 0o0o0o0o0o0o0o

### PR DESCRIPTION
**Pull request by NRGJobro**

### CODE REVIEW

**Comment by Intoprelised** [comment]
nice

**Comment by GodGamer029** [comment]
Classic lava dupe back in the game

**Comment by Intoprelised** [comment]
why would u close this lol

**Comment by NRGJobro** [comment]
:( y did it get closed?

**Comment by GodGamer029** [comment]
Wait what this actually works

**Comment by GodGamer029** [comment]
this is ridiculous, this code is telling the game to destroy the item

**Pull request merged**
