### PR TITLE
Added Decent Rotations

### PR DESCRIPTION
**Pull request by Intoprelised**
Horion has never had killaura rotations so here are some simple but effectives ones

### CODE REVIEW

**Comment by dexteratyt** [comment]
rip dexter :(

**Comment by Intoprelised** [comment]
> rip dexter :(

whats ur new discord?

**Comment by dexteratyt** [comment]
i dont have rn i got the "ur account looks sus Please verify ur account by using ur number" and i used mine in my other account (termed) :/

**Comment by Intoprelised** [comment]
> i dont have rn i got the "ur account looks sus Please verify ur account by using ur number" and i used mine in my other account (termed) :/

i dont have an account either, in the past 5 days ive gotten disabled 3 times

**Comment by dexteratyt** [comment]
same my plan is to make tudou a private client

**Comment by dexteratyt** [comment]
when i get my account back

**Comment by Intoprelised** [comment]
> same my plan is to make tudou a private client

same for ghost or discountinued, i have a probleme, i really need someone to make me a discord account bec discord dosnt let me, idk who can do it

**Comment by Roonicks** [comment]
> > mismo mi plan es hacer de tudou un cliente privado
> 
> Lo mismo para fantasma o descontado, tengo un problema, realmente necesito que alguien me haga una cuenta de discordia porque la discordia no me deja, no sé quién puede hacerlo

I could do it for you, but do you have mail?

**Comment by Intoprelised** [comment]
> > > mismo mi plan es hacer de tudou un cliente privado
> > 
> > 
> > Lo mismo para fantasma o descontado, tengo un problema, realmente necesito que alguien me haga una cuenta de discordia porque la discordia no me deja, no sé quién puede hacerlo
> 
> I could do it for you, but do you have mail?

thanks for offering but i got one now :)

**Pull request merged**
