### PR TITLE
killaura no longer attacks arrows

### PR DESCRIPTION
**Pull request by MrDiamond64**

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
someone just make an isMob func at this point lmao

**Comment by Intoprelised** [comment]
ikr

**Comment by Intoprelised** [comment]
i might

**Comment by N0tExisting** [comment]
> someone just make an isMob func at this point lmao

I'd say we need a `shouldAttack` function, not specificaly to mobs (armorstands, leads, etc.)

**Comment by Deadly420** [comment]
add this

if (currentEntity->getEntityTypeId() == 51)  // NPC
			return;

**Comment by Intoprelised** [comment]
> > someone just make an isMob func at this point lmao
> 
> I'd say we need a `shouldAttack` function, not specificaly to mobs (armorstands, leads, etc.)

should i make that

**Review by ZodiussDev — APPROVED** [review]

**Pull request merged**
