### PR TITLE
Added Ender Chests to ChestAura

### PR DESCRIPTION
**Pull request by Intoprelised**
if u want i can make it a bool

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
what is the point of that??

**Comment by richardletshacks** [comment]
> what is the point of that??

I can imagine some servers using ender chests as higher tier chests or something

**Comment by Intoprelised** [comment]
> > what is the point of that??
> 
> I can imagine some servers using ender chests as higher tier chests or something

Hive does

**Comment by Intoprelised** [comment]
il open a fork instead

**Pull request closed without merging**
