### PR TITLE
Some 1.16.220 fixes

### PR DESCRIPTION
**Pull request by Imrglop**
needed to remake the pull request

### CODE REVIEW

**Comment by brampedgex** [comment]
That ClientInstance signature looks like it won't survive an update since it has the alignment padding in it.

**Comment by Imrglop** [comment]
> That ClientInstance signature looks like it won't survive an update since it has the alignment padding in it.

Yep it does, I'll get another

**Comment by Imrglop** [comment]
Nvm, couldn't gen one that doesn't need the padding. It needs it to be unique (at least it's better than using an address as a base)

**Comment by Imrglop** [comment]
Should I use an address offset instead (like it was)?

**Pull request merged**
