### PR TITLE
Update discord link & move CrystalAura to combat

### PR DESCRIPTION
**Pull request by GrelTheL**
penis

### CODE REVIEW

**Comment by ghost** [comment]
Vouch for his contributer point addiction

**Comment by GrelTheL** [comment]
@SurvirvorHRG accept pr

**Comment by GrelTheL** [comment]
also moved crystalaura to combat 😳

**Comment by XBLADE1** [comment]
you should let use change the color of the menu like have a option set to were we can open it and chose the colour like rainbow orange yellow red dark blue light blue grey black

**Comment by GodGamer029** [comment]
thank you grelom, very cool

**Pull request merged**
