### PR TITLE
Added NoSwing option to killaura

### PR DESCRIPTION
**Pull request by Intoprelised**
this will work better once killaura actually swings lol

### CODE REVIEW

**Comment by FloppyDolphin57** [comment]
there is a no swing module already

**Comment by Intoprelised** [comment]
yeah but thats broken

**Comment by FloppyDolphin57** [comment]
> yeah but thats broken

how do you know its broken? killaura doesnt even swing rn so you can even test it

**Comment by Intoprelised** [comment]
> > yeah but thats broken
> 
> how do you know its broken? killaura doesnt even swing rn so you can even test it

that is true, il consider that

**Comment by richardletshacks** [comment]
instead of making that an option, make an actual noswing by hooking the localplayers swing function

**Pull request closed without merging**
