### PR TITLE
remove nukkit dupe

### PR DESCRIPTION
**Pull request by lmaodick1239**

### CODE REVIEW

**Comment by GreenPlumTea** [comment]
Rather than removal, what about options?

**Comment by FloppyDolphin57** [comment]
> Rather than removal, what about options?

Nukkit dupe was patched so there no point in having it

**Comment by MrDiamond64** [comment]
> 
> Nukkit dupe was patched so there no point in having it

But Nukkit dupe works on Mineville. Mineplex and Galaxite

**Comment by question-pixel** [comment]
bruh why this a lol priority?

**Pull request closed without merging**
