### PR TITLE
Tower Keybinds fixed

### PR DESCRIPTION
**Pull request by Greloom-Yeet**
UwU

### CODE REVIEW

**Comment by Greloom-Yeet** [comment]
Sir, accept the fucking pull request @SurvirvorHRG

**Comment by Greloom-Yeet** [comment]
Sir, I fixed NoFall fucking up the Elytra by setting fallDistance to 0.5, can you accept the goddamn pull request @SurvirvorHRG @richardletshacks

**Comment by ghost** [comment]
I agree

**Comment by Greloom-Yeet** [comment]
I agree aswell

**Comment by ghost** [comment]
same bro

**Comment by ghost** [comment]
Sir, this piece of software instructions is also designed to give the user an advantage in a game known widely as Minecraft should be merged into the main, central repository. As such, I would like to request that YOU FUCKING PULL IT.

**Comment by Greloom-Yeet** [comment]
Sir, why the fuck did you close the PR

**Pull request closed without merging**
