### PR TITLE
Added ores to fucker

### PR DESCRIPTION
**Pull request by Intoprelised**
Not sure if it works on latest version

### CODE REVIEW

**Comment by richardletshacks** [comment]
I don't see why you would add this to fucker

**Comment by Intoprelised** [comment]
> I don't see why you would add this to fucker

For hive skywars so u can mine the ores that give you hearts, tools/armor and other stuff

**Comment by yeeterlol** [comment]
> > I don't see why you would add this to fucker
> 
> For hive skywars so u can mine the ores that give you hearts, tools/armor and other stuff

Pretty true, it could also be used for mining

**Comment by LeonetKenner** [comment]
wish if horion atleast updates to 1.16.210 lmao

**Comment by Intoprelised** [comment]
> wish if horion atleast updates to 1.16.210 lmao

true

**Comment by LeonetKenner** [comment]
Someone pls Update horion to 1.16.221.1 lol

**Comment by Intoprelised** [comment]
well richard no like it oof

**Comment by LeonetKenner** [comment]
:/

**Pull request closed without merging**
