### PR TITLE
Update Vars

### PR DESCRIPTION
**Pull request by Damakermiddle**

### CODE REVIEW

**Comment by Damakermiddle** [comment]
i merged into the wrong branch but ok

**Comment by richardletshacks** [comment]
Some of these vars are still shit, don't name them just x

**Comment by Damakermiddle** [comment]
ok

**Comment by Damakermiddle** [comment]
imma fix it in 20 mins @richardletshacks

**Comment by Damakermiddle** [comment]
@richardletshacks ight im done

**Comment by Damakermiddle** [comment]
@richardletshacks Would u make a server friendly version of this???
As in like have no 'hacks'.  Just things that make the game more easier like BadLion client.
(autosprint, fullbright)

**Comment by richardletshacks** [comment]
What do you mean?

**Comment by Damakermiddle** [comment]
As in it doesn't have any hacks that will get you banned, thus server friendly.
It should be easy, as all you need to do is make a cpp file that disables the modules, or straight up delete it.  Make another branch or something like that.
@richardletshacks

**Comment by Damakermiddle** [comment]
O WOW LOOK WHAT I FOUND FUK U
image

**Comment by richardletshacks** [comment]
> As in it doesn't have any hacks that will get you banned, thus server friendly.
> It should be easy, as all you need to do is make a cpp file that disables the modules, or straight up delete it. Make another branch or something like that.

no

**Comment by Damakermiddle** [comment]
y

**Comment by Damakermiddle** [comment]
ight imma do it myself lol

**Comment by richardletshacks** [comment]
Why a new branch? Just don't turn on the obvious modules

**Comment by Damakermiddle** [comment]
*accidentally presses 'p'*

**Comment by richardletshacks** [comment]
You know that you can unbind modules?

**Comment by Damakermiddle** [comment]
yes but i wouldnt do that because i dont want to rebind them when i join 2b2tpe

**Comment by richardletshacks** [comment]
well thats your problem I guess

**Comment by Damakermiddle** [comment]
ight imma make me own

**Comment by NewGrelAltNewLife** [comment]
👍 Code seems okay.

**Comment by Damakermiddle** [comment]
@NewGrelAltNewLife Can u help me find more???

**Comment by NewGrelAltNewLife** [comment]
@Damakermiddle Will do.

**Comment by Damakermiddle** [comment]
ight wtf is this
```
<<<<<<< master
		C_MovePlayerPacket moveplayerPacket1 = C_MovePlayerPacket();
		if (moveplayerPacket1.vTable == packet->vTable)
=======
		C_MovePlayerPacket movePacket = C_MovePlayerPacket();
		if (movePacket.vTable == packet->vTable)
>>>>>>> master
```

**Comment by ghost** [comment]
```
<<<<<<< master
		C_MovePlayerPacket moveplayerPacket1 = C_MovePlayerPacket();
		if (moveplayerPacket1.vTable == packet->vTable)
=======
		C_MovePlayerPacket movePacket = C_MovePlayerPacket();
		if (movePacket.vTable == packet->vTable)
>>>>>>> master
```
to
```
		C_MovePlayerPacket moveplayerPacket1 = C_MovePlayerPacket();
		if (moveplayerPacket1.vTable == packet->vTable)
```

**Comment by Damakermiddle** [comment]
k

**Comment by Damakermiddle** [comment]
done

**Comment by Damakermiddle** [comment]
@SurvirvorHRG ok im done kek

**Comment by ghost** [comment]
have you tested it

**Comment by Damakermiddle** [comment]
@d1gress ye
```1>------ Build started: Project: Horion, Configuration: Debug x64 ------
1>AutoTotem.cpp
1>MSVCRTD.lib(initializers.obj) : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
1>Horion.vcxproj -> C:\Users\Dell Precision\IdeaProjects\Client\x64\Debug\Horion.dll
1>Done building project "Horion.vcxproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========```

**Comment by Damakermiddle** [comment]
Imma make a branch for the inclient chat, making it into a pullRequest so other ppl can help when they want.

**Comment by Damakermiddle** [comment]
@SurvirvorHRG was being meme so he didn't want to merge it before it was too late closing.

**Pull request closed without merging**
