### PR TITLE
You can fly with freecam | canFLy onEnable.

### PR DESCRIPTION
**Pull request by hrkyr**

### CODE REVIEW

**Comment by hrkyr** [comment]
1337 HACKER SKILLS DREAM MODE ACTIVATED MLG WATER CLUTCH DREAM NOT FOUND RULE 34 XXX BOAT CLUTCH DREAM SMP TOMMY TUBBO DISKS

**Comment by Mixu78** [comment]
Won't work as the sigs are fucked

**Comment by richardletshacks** [comment]
``canFly = true`` is set every tick anyways, so this is not needed.

**Comment by N0tExisting** [comment]
Just Force enable Glide, that will result in the same effect

**Pull request closed without merging**
