### PR TITLE
localPlayerUpdateFromCam sig

### PR DESCRIPTION
**Pull request by FloppyDolphin57**

### CODE REVIEW

**Comment by Intoprelised** [comment]
nice

**Comment by Wendys-corp** [comment]
fish bucket nbt works now can you update cbe to use fish bucket nbt

**Comment by FloppyDolphin57** [comment]
> fish bucket nbt works now can you update cbe to use fish bucket nbt

fish buckets are patched they have no nbt data

**Comment by Wendys-corp** [comment]
> > fish bucket nbt works now can you update cbe to use fish bucket nbt
> 
> fish buckets are patched they have no nbt data

its no longer patched i can use it right now I was able to spawn a horse using nbt load with nbt data

to prove my point use this
{Attributes:[{Base:0.408322f,Current:5f,Max:5f,Name:"minecraft:horse.jump_strength"},{Base:0.133367f,Current:50f,Max:"3.4028235E38f",Name:"minecraft:movement"}],CustomName:"Zippy",EntityType:125,Invunerable:1b,RepairCost:0,definitions:["+minecraft:strider"],display:{Lore:["Â§lHacked By Fry"],Name:"Zippy the Strider"}}

use nbt load and it will give u a bucket with nbt

**Comment by FloppyDolphin57** [comment]
> > > fish bucket nbt works now can you update cbe to use fish bucket nbt
> > 
> > 
> > fish buckets are patched they have no nbt data
> 
> its no longer patched i can use it right now I was able to spawn a horse using nbt load with nbt data
> 
> to prove my point use this
> {Attributes:[{Base:0.408322f,Current:5f,Max:5f,Name:"minecraft:horse.jump_strength"},{Base:0.133367f,Current:50f,Max:"3.4028235E38f",Name:"minecraft:movement"}],CustomName:"Zippy",EntityType:125,Invunerable:1b,RepairCost:0,definitions:["+minecraft:strider"],display:{Lore:["Â§lHacked By Fry"],Name:"Zippy the Strider"}}
> 
> use nbt load and it will give u a bucket with nbt

that nbt doesnt even have a bucket tag in it...

**Comment by Wendys-corp** [comment]
> > > > fish bucket nbt works now can you update cbe to use fish bucket nbt
> > > 
> > > 
> > > fish buckets are patched they have no nbt data
> > 
> > 
> > its no longer patched i can use it right now I was able to spawn a horse using nbt load with nbt data
> > to prove my point use this
> > {Attributes:[{Base:0.408322f,Current:5f,Max:5f,Name:"minecraft:horse.jump_strength"},{Base:0.133367f,Current:50f,Max:"3.4028235E38f",Name:"minecraft:movement"}],CustomName:"Zippy",EntityType:125,Invunerable:1b,RepairCost:0,definitions:["+minecraft:strider"],display:{Lore:["Â§lHacked By Fry"],Name:"Zippy the Strider"}}
> > use nbt load and it will give u a bucket with nbt
> 
> that nbt doesnt even have a bucket tag in it...

i gave you the wrong nbt here is the right one use nbt load on it

{Count:1b,Damage:5s,Name:"minecraft:bucket",tag:{EntityType:65,Attributes:[{Current:40.0f,Max:40.0f,Base:1.0f,Name:"minecraft:attack_damage"},{Current:2048.0f,Max:2048.0f,Base:16.0f,Name:"minecraft:follow_range"},{Current:0.5f,Max:"3.4028235E38f",Base:0.1f,Name:"minecraft:movement"},{Current:1.0f,Max:1.0f,Base:0.0f,Name:"minecraft:knockback_resistance"},{Current:400.0f,Max:"3.4028235E38f",Base:20.0f,Name:"minecraft:health"}],Mainhand:[{Count:64b,tag:{ench:[{id:17s,lvl:32767s},{id:18s,lvl:20s},{id:9s,lvl:32767s},{id:9s,lvl:32767s},{id:13s,lvl:32767s},{id:14s,lvl:20s},{id:26s,lvl:1s},{id:15s,lvl:32767s},{id:12s,lvl:32767s}],RepairCost:0,Damage:0},Damage:0s,CanPlaceOn:[bedrock,end_portal_frame,barrier],CanDestroy:[bedrock,end_portal_frame,barrier],Name:"minecraft:diamond_axe"}],CustomName:"Ok....BOOMer",Invunerable:1b,definitions:["+minecraft:chicken","+minecraft:chicken_adult"]}}

**Pull request merged**
