### PR TITLE
added selfhurt to the fly modules

### PR DESCRIPTION
**Pull request by MrDiamond64**
can be used to bypass some (bad) fly anticheats

### CODE REVIEW

**Comment by Intoprelised** [comment]
> can be used to bypass some (bad) fly anticheats
> 
> packet > badman
no, packet is not better then badman

**Comment by OldGreggo5081** [comment]
> can be used to bypass some (bad) fly anticheats
> 
> packet > badman

i dont even know who you are

**Comment by MrDiamond64** [comment]
just wanted to piss of some people with that :)

**Comment by OldGreggo5081** [comment]
lmao

**Comment by Intoprelised** [comment]
> just wanted to piss of some people with that :)

image

U did your job LOL

**Comment by Intoprelised** [comment]
@MrDiamond64 whats ur discord?

**Comment by MrDiamond64** [comment]
@Intoprelised why?

**Comment by Intoprelised** [comment]
> @Intoprelised why?
Just wondering

**Pull request closed without merging**
