### PR TITLE
Fix #266

### LINKED ISSUE #202: Glide
While using glide, you are able to talk. 
While you're doing this if you press spacebar, w, a, s, d, or shift then it will move you inside of the game.

### LINKED ISSUE #266: When using glide the shift and space keys work in chat
**Describe the bug**

**To Reproduce**
1. Enable Glide
2. Go To Chat
3. Press the space or shift keys

**Expected behavior**
You dont move

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
Fix Glide working on all screens

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
it turns out #202 actually has nothing to do with the issue this pr's fixing

**Review by richardletshacks — COMMENTED** [review]
you could also just add the check at the beginning, `if(!g_Data.canUseMoveKeys()) return;`

**Comment by Johnmacrocraft** [comment]
@richardletshacks That's what I did first, but that will make the player fall when they open GUI

**Comment by Johnmacrocraft** [comment]
> gm->player->velocity.y = glideModEffective;

This code needs to be placed outside the canUseMoveKeys check

**Pull request merged**
