### PR TITLE
Fixed .give nbt support. ex: .give dirt 1 0 1

### PR DESCRIPTION
**Pull request by NRGJobro**
Fixed .give nbt support. ex: .give dirt 1 0 1. Credits to theclashingfritz for the multiple stack support pull.

### CODE REVIEW

**Comment by Intoprelised** [comment]
pog

**Comment by NRGJobro** [comment]
WTF, y fail?

**Comment by NRGJobro** [comment]
OOOOH, I never added the .h. My bad.

**Comment by NRGJobro** [comment]
Ok, fixed some glitches, and added the .h

**Pull request merged**
